###########################
#       PocketHorses      #
#    Configuration file   #
###########################

# What type of storage should the plugin use?
#
# Possible options:
# - MySQL (remote database, requires connection information)
# - SQLite (local database, requires no configuration)
# - JSON (.json file, requires no configuration)
#
Storage:
  Type: 'SQLite'
  MySQL: # MySQL's connection information, ignore if storage type is not 'MySQL'
    Host: 'localhost'
    Port: 3306
    Database: 'pockethorses'
    Username: 'root'
    Password: ''

Options:
  Language: 'en' # The language used for the plugin messages
  Economy:
    Type: 'Vault' # The plugin used to manage the plugin economy, can be 'Vault', 'PlayerPoints' or 'CoinsEngine'.
    CoinsEngine-Currency: 'coins' # CoinsEngine currency name, you can leave blank if you don't use CoinsEngine as your economy type.
  Shop-Enabled: true # If enabled, players will be able to purchase horses through the /horses shop command
  More-Horses-At-Time: true # If enabled, players will be able to spawn more than one horse at a time
  Play-Sound-When-Buy: true # If enabled, a sound will be played after purchasing a horse (see Horse-GUI section)
  Allow-Player-Damage: false # If enabled, players will be able to damage horses
  More-Than-Once-Same-Horse: false # If enabled, players will be able to own the same horse more than once
  Update-Message-On-Join: true # If enabled, OP players will receive a message when a new update is available
  Auto-Recall-Range: 30 # The range of distance blocks beyond which the horse will teleport from the player if Auto-Recall is active
  Action-Bar-While-Riding: true # If enabled, a message will be shown in action bar when the player rides a horse
  Action-Bar-Message: '&a&l%speed% KM/H' # The message to show (works only if Action-Bar-While-Riding is true)
  Display-HP-In-Name: true # If enabled, health will be shown in the spawned horse's name
  Display-HP: '&c%health% HP ❤' # The message that includes horse health
  Use-Recall-Permission: false # If enabled, players will need to have 'pockethorses.recall' permission to recall horses
  Horse-Limit: 100 # The maximum number of horses a player can have. It can be chosen for each player with the permission pockethorses.max.<limit>.

# Customize aliases of plugin commands
Commands:
  PocketHorses:
    Aliases:
      - 'ph'
      - 'horsesadmin'
  Horses:
    Aliases:
      - 'horse'

# Customize the menu that is opened after the /horses command
Horses-GUI:
  Title: 'My horses' # The GUI title
  Use-Permission: false # If enabled, players will need to have 'pockethorses.gui.horses' permission to use this GUI
  Size:
    Rows: 5 # The horizontal lines of the GUI, can be up to 6
    Columns: 9 # The vertical columns of the GUI, there are normally 9
  Horse-Item:
    Name: '%displayName%' # The name of the item representing the horse in the GUI
    Material: IRON_HORSE_ARMOR # The item type, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    Lore: # The item description
      - '&7Speed: &f%speed% km/h'
      - '&7Owner: &f%owner%'
      - ''
      - '&a&lLeft-Click to spawn!'
      - '&a&lRight-Click to recycle!'

# Customize the menu that is opened after you click on a horse
Horse-GUI:
  Title: 'Horse' # The GUI title
  Use-Permission: false # If enabled, players will need to have 'pockethorses.gui.horse' permission to use this GUI
  Size:
    Rows: 5 # The horizontal lines of the GUI, can be up to 6
    Columns: 9 # The vertical columns of the GUI, there are normally 9
  Auto-Recall:
    Name: '&9&lAuto-Recall'
    Material: LEAD
    Enabled-Lore:
      - '&aENABLED'
    Disabled-Lore:
      - '&cDISABLED'
  Horse-Info:
    Name: '&a%player%''s &fHorse'
    Material: PAPER # The item type, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  Horse-Storage:
    Name: '&6&lHorse Storage'
    Material: CHEST
  Change-Name:
    Name: '&a&lChange the name'
    Material: NAME_TAG
  Make-Sit:
    Name: '&e&lMake sit'
    Material: SADDLE
  Get-Up:
    Name: '&e&lGet up'
    Material: SADDLE
  Set-Speed:
    Name: '&b&lSet speed'
    Material: IRON_HORSE_ARMOR
  Remove:
    Name: '&c&lRemove'
    Material: BARRIER
  Glow:
    Name: '&f&lMake glow'
    Material: GLOWSTONE_DUST

# Customize what is shown after the /pockethorses list command
Horses-List:
  Header: '&6List of loaded horses:' # The message preceding the list
  Horse: '&8- &e%horse%' # The message representing a loaded horse

Storage-GUI:
  Title: 'Horse Storage' # The GUI title
  Use-Permission: false # If enabled, players will need to have 'pockethorses.gui.storage' permission to use this GUI
  Size:
    Rows: 2 # The horizontal lines of the GUI, can be up to 6
    Columns: 9 # The vertical columns of the GUI, there are normally 9

Shop-GUI:
  Title: 'Shop' # The GUI title
  Use-Permission: false # If enabled, players will need to have 'pockethorses.gui.shop' permission to use this GUI
  Buy-Sound: BLOCK_ANVIL_USE # The sound that is played when a horse is purchased (the Play-Sound-When-Buy option needs to be enabled), see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  Size:
    Rows: 5
    Columns: 9
  Horse-Item:
    Name: '%displayName%'
    Material: DIAMOND_HORSE_ARMOR
    Lore:
      - '&7Speed: &f%speed% km/h'
      - '&7Price: &f%price%$'
      - ''
      - '&a&lClick to buy!'

Editor-GUI:
  Main:
    Title: 'Editor' # The GUI title
    Size:
      Rows: 6 # The horizontal lines of the GUI, can be up to 6
      Columns: 9 # The vertical columns of the GUI, there are normally 9
    Horse-Item:
      Name: '&6&l%id%'
      Material: GOLDEN_HORSE_ARMOR
      Lore:
        - '&7Display Name: &e%displayName%'
        - '&7Color: &e%color%'
        - '&7Style: &e%style%'
        - '&7Speed: &e%speed%'
        - '&7Jump Strength: &e%jumpStrength%'
        - '&7Max Health: &e%maxHealth%'
        - '&7Buyable: &e%buyable%'
        - '&7Price: &e%price%'
        - '&7Permission: &e%permission%'
        - '&7Storage: &e%storage%'
        - '&7Model: &e%model%'
        - '&7Cooldown: &e%cooldown%'
        - ''
        - '&6&lLeft click to edit!'
        - '&6&lRight click to delete!'
    New-Horse:
      Name: '&6&lCreate horse'
      Material: ANVIL
      Lore: []
    Previous-Page:
      Name: '&ePrevious page'
      Material: ARROW
      Lore: []
    Next-Page:
      Name: '&eNext page'
      Material: ARROW
      Lore: []
  Editing-GUI:
    Title: 'Editing Horse: %id%'
    Size:
      Rows: 6
      Columns: 9
    Display-Name:
      Name: '&f&lDisplay Name'
      Material: NAME_TAG
      Lore:
        - '&7The displayed name of the horse.'
        - '&7Current: &f%displayName%'
        - ''
        - '&6&lClick to set!'
    Color:
      Name: '&f&lColor'
      Material: CYAN_DYE
      Lore:
        - '&7The color of the horse.'
        - '&7Current: &f%color%'
        - ''
        - '&6&lClick to set!'
    Style:
      Name: '&f&lStyle'
      Material: FIREWORK_STAR
      Lore:
        - '&7The style of the horse.'
        - '&7Current: &f%style%'
        - ''
        - '&6&lClick to set!'
    Speed:
      Name: '&f&lSpeed'
      Material: IRON_HORSE_ARMOR
      Lore:
        - '&7The movement speed of the horse (in km/h).'
        - '&7Current: &f%speed%'
        - ''
        - '&6&lClick to set!'
    Jump-Strength:
      Name: '&f&lJump Strength'
      Material: FIREWORK_ROCKET
      Lore:
        - '&7The jumping strength of the horse.'
        - '&7Current: &f%jumpStrength%'
        - ''
        - '&6&lClick to set!'
    Max-Health:
      Name: '&f&lMax Health'
      Material: REDSTONE_TORCH
      Lore:
        - '&7The maximum health of the horse.'
        - '&7Current: &f%maxHealth%'
        - ''
        - '&6&lClick to set!'
    Buyable:
      Name: '&f&lIs buyable?'
      Material: OAK_SIGN
      Lore:
        - '&7If enabled, the horse can be purchased.'
        - '&7Current: &f%buyable%'
        - ''
        - '&6&lClick to set!'
    Price:
      Name: '&f&lPrice'
      Material: EMERALD
      Lore:
        - '&7The purchase price of the horse.'
        - '&7Current: &f%price%'
        - ''
        - '&6&lClick to set!'
    Permission:
      Name: '&f&lPermission'
      Material: SUNFLOWER
      Lore:
        - '&7If enabled, the horse will require a permission to be used.'
        - '&7Current: &f%permission%'
        - ''
        - '&6&lClick to set!'
    Storage:
      Name: '&f&lStorage'
      Material: CHEST
      Lore:
        - '&7If enabled, the horse will have a storage.'
        - '&7Current: &f%storage%'
        - ''
        - '&6&lClick to set!'
    Recyclable:
      Name: '&f&lIs recyclable?'
      Material: BRICK
      Lore:
        - '&7If enabled, the horse can be recycled.'
        - '&7Current: &f%recyclable%'
        - ''
        - '&6&lClick to set!'
    Recycle-Price:
      Name: '&f&lRecycle Price'
      Material: EGG
      Lore:
        - '&7The money given to the player after recycling this horse.'
        - '&7Current: &f%recyclePrice%'
        - ''
        - '&6&lClick to set!'
    Model:
      Name: '&f&lModelEngine Model'
      Material: DIAMOND_HORSE_ARMOR
      Lore:
        - '&7The ModelEngine model used for the horse (optional).'
        - '&7Current: &f%model%'
        - ''
        - '&6&lClick to set!'
    Cooldown:
      Name: '&f&lCooldown'
      Material: CLOCK
      Lore:
        - '&7The time to wait before spawning this horse again (optional).'
        - '&7Current: &f%cooldown%'
        - ''
        - '&f&lClick to set!'
    Back:
      Name: '&c&lBack'
      Material: ARROW
      Lore: []
    Confirm:
      Name: '&a&lConfirm'
      Material: NETHER_STAR
      Lore: []
  Color-GUI:
    Title: 'Select color'
    Size:
      Rows: 4
      Columns: 9
    Color-Item:
      Name: '&f&l%color%'
      Material: PAPER
      Lore:
        - '&7Click to select this color.'
  Style-GUI:
    Title: 'Select style'
    Size:
      Rows: 4
      Columns: 9
    Style-Item:
      Name: '&f&l%style%'
      Material: PAPER
      Lore:
        - '&7Click to select this style.'
  Model-GUI:
    Title: 'Select model'
    Size:
      Rows: 4
      Columns: 9
    Model-Item:
      Name: '&f&l%model%'
      Material: PAPER
      Lore:
        - '&7Click to select this model.'

Confirm-GUI:
  Title: 'Confirm' # The GUI title
  Size:
    Rows: 5 # The horizontal lines of the GUI, can be up to 6
    Columns: 9 # The vertical columns of the GUI, there are normally 9
  Are-You-Sure:
    Name: '&6&lAre you sure?'
    Material: PAPER
    Lore: []
  Confirm:
    Name: '&a&lConfirm'
    Material: LIME_STAINED_GLASS_PANE
    Lore: []
  Cancel:
    Name: '&c&lCancel'
    Material: RED_STAINED_GLASS_PANE
    Lore: []

Vouchers:
  Opening:
    Title: '&a&lOpening voucher..' # The title to send while opening a voucher
    Sub-Title: '&a&k::::::::' # The subtitle to send while opening a voucher
    Delay: 5 # The time in seconds to wait before revealing the voucher prize
    Sound: BLOCK_CHEST_OPEN # The sound to be played when opening a voucher, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  Reward:
    Title: '&a&lVoucher opened!' # The title to be sent when the prize is revealed
    Sub-Title: '&aYou won &r%reward%' # The subtitle to be sent when the prize is revealed
    Sound: ENTITY_PLAYER_LEVELUP # The sound to be played when the prize is revealed, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  List:
    Header: '&6List of loaded vouchers:' # The message preceding the list
    Voucher: '&8- &e%voucher%' # The message representing a loaded voucher

Items-List:
  Header: '&6List of loaded items:' # The message preceding the list
  Item: '&8- &e%item% &8| §e%type%' # The message representing a loaded item