name: PocketHorses
version: 1.5.0
main: it.pika.pockethorses.PocketHorses
api-version: '1.13'
author: Pika
softdepend: [Vault, PlaceholderAPI]
description: PocketHorses plugin made with love and pizza by Pika
