name: PocketHorses
version: 1.8.3.1
main: it.pika.pockethorses.Main
api-version: '1.13'
author: Pika
softdepend: [Vault, PlaceholderAPI, WorldGuard, ModelEngine, PlayerPoints]
description: PocketHorses plugin made with love and pizza by Pika
libraries:
  - com.zaxxer:HikariCP:5.0.1
